### ISSUE TITLE
Update FR locale

### ISSUE THREAD

**Issue by Lonak** [Mibew/i18n#7]
Hi,

I'm rather new to the way Github works for participating.
I've updated the French translation quite a bit, although some work remain to do. 

WHAT'S BEEN DONE:
- Punctuation errors fixed;
- Translated unstranslated strings;
- Fixed mistranslations;
- Fixed capital letters missing accents;

TO DO:
- There are still a good amount of more technical strings left untranslated.;
- There are surely other mistranslations;
- Consistency check;

Inside the ZIP is a PO file downloaded from the Mibew translation dashboard. I did my edits within the software (self-installed) using Mibew 2.2.0. Hoping this helps.

[translation-fr.zip](https://github.com/Mibew/i18n/files/760665/translation-fr.zip)

**Comment by faf** [comment]
Thank you. :)

We'll take a look at your contribution in the near future.

**Comment by faf** [comment]
I've just updated the translation.

One small note. One should not translate the domain of `example.com`, since it's a special domain [reserved to be an example](http://www.iana.org/domains/reserved) in manuals, etc.
